### ISSUE TITLE
El valor de una operación matemática...

### ISSUE THREAD

**Issue by MARSFOREVER472** [MARSFOREVER472/Practicas#1]
...No imprime por consola, me salía todo en blanco, si es que mi compañero organizador me puede ayudar un poco en esto!

Saludos!

**Comment by Autinfit** [comment]
Estimado:

Disculpa por no responder este mensaje, entiendo que fue hace 2 semanas, pero te voy responder sin ningún inconveniente este mensaje, entonces si no imprime por consola esto de las operaciones matemáticas, haz esto lo siguiente:

Mediante una iteración "switch", para que pueda desplegar el resultado:

return console.log(a + b); // RETORNA EL VALOR DE LA SUMA.

Espero te sirva de ayuda!

Saludos!

**Comment by MARSFOREVER472** [comment]
Muchas gracias, estimado!!!!!

Te perdono por esta vez por la indisciplina que tuviste conmigo!

Saludos!
